### ISSUE TITLE
7clicker javaw process opening and closing after 1 second

### ISSUE THREAD

**Issue by 7kPing10FPS** [Ruffian7/7Clicker#4]
Exception in thread "main" java.lang.NoClassDefFoundError: org/jnativehook/NativeHookException
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
Caused by: java.lang.ClassNotFoundException: org.jnativehook.NativeHookException
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 3 more

**Comment by 7kPing10FPS** [comment]
I'm on Win7 x64

**Comment by swordsent** [comment]
did you solve the issue?

**Comment by 7kPing10FPS** [comment]
honestly? I don't remember making this thread orz
cheers mate 🎉
