### ISSUE TITLE
Class Errors?

### ISSUE THREAD

**Issue by jumpy72red** [Ruffian7/7Clicker#6]
I use Linux, so I executed the file from terminal. I got this error:
`harry@Debian:~/Downloads/7Clicker-master$ java -jar 7Clicker.jar 
Exception in thread "main" java.lang.NoClassDefFoundError: org/jnativehook/NativeHookException
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
Caused by: java.lang.ClassNotFoundException: org.jnativehook.NativeHookException
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 3 more
`
I ran the 7Clicker.jar file, am I running the wrong one or something?

**Comment by gingyzhere** [comment]
hi harry debian @harry linux
